### ISSUE TITLE
Redirected pages get indexed twice

### ISSUE THREAD

**Issue by ktallafus** [dachcom-digital/pimcore-lucene-search#64]
We get one entry for the original page and one entry for the target page. Redirect should be followed but not indexed

**Comment by LosHawlos** [comment]
There is an other big problem with the spider on redirects:
They get followed and parsed in the context of the Pimcore-Domain, not the domain of the redirect target.

Example:
Say our pimcore runs on
www.aaa.com
and contains a href that is stored in a Pimcore DocumentLink
www.aaa.com/redir  => www.bbb.com

The crawler then downloads www.aaa.com/redir  with the redirect followed, but all relative links that are in the page www.bbb.com are added to the spider queue using the domain www.aaa.com instead of www.bbb.com.
So the the link www.bbb.com/xyz is enqueued as www.aaa.com/xyz which is the later called by the indexer but only gives a 404 error.

**Comment by solverat** [comment]
@LosHawlos sorry for asking, but are you really using the pimcore 5 version of lucene search? Since we have a bug (#74) in the host configuration, it was never possible to crawl another domain rather than the given seed.

**Comment by solverat** [comment]
Ok, i pushed something for the redirect issue which needs some explanation: I changed the guzzle client `allow_redirects` options to `false`. I'm going to 


### allow_redirects: true (Before)
- Guzzle crawls a redirect `xy.com/redirect`
- Redirects are allowed -> guzzle follows redirects to `/xy.com/redirect/sub-redirect/page` until a `200` response is available
- Spider still awaits `xy.com/redirect` -> content from guzzle returns, **but** from the last valid resource (status `200`)
- Spider stores resources as `xy.com/redirect` **but** with content from `/xy.com/redirect/sub-redirect/page`
- Discoverer searches for another links in given resource and so on

### allow_redirects: false (Now)
- Guzzle crawls a redirect `xy.com/redirect`
- Redirects are not allowed -> guzzle returns a simple resource with a including `Redirecting to` message.
- Spider stores resources as `xy.com/redirect`
- Discoverer searches for another links in given redirect resource -> redirect link is available -> follow it.

**Comment by solverat** [comment]
@LosHawlos The original topic of this ticket has been resolved. Feel free to open another ticket regarding your domain issues (if it still exists).
